this.examples=[
	{
		"name": "Kind - Eltern (griechische Goetter und Helden)",
		"description": "Ein einf%uuml;hrendes Beispiel zur Rekursion in Datalog.",
		"source": "&Uml;bung zur Vorlesung",
		"ruleset": [
			"kindEltern(zeus,leto,apollon).",
			"kindEltern(zeus,leto,artemis).",
			"kindEltern(zeus,maia,hermes).",
			"kindEltern(koios,phoebe,leto).",
			"kindEltern(atlas,pleione,maia).",
			"kindEltern(kronos,rheia,hades).",
			"kindEltern(kronos,rheia,poseidon).",
			"kindEltern(kronos,rheia,zeus)."
		],
		"query": "kindEltern(zeus,leto,KIND)"
	},
	{
		"name": "Umlaufbahnen von kosmologischen Objekten",
		"description": "Umlaufbahnen von kosmologischen Objekten",
		"source": "Rafael Caballero-Rold\u0027an, 2007",
		"ruleset": [
			"% Orbits of cosmological objects",
			"% Rafael Caballero-Rold\u0027an, 2007",
			"",
			"star(sun).",
			"",
			"orbits(earth, sun).",
			"orbits(moon, earth).",
			"orbits(X,Y) :-", 
			"  orbits(X,Z), ",
			"  orbits(Z,Y). % This is correct",
			"%  orbits(Y,Z). % This is an error",
			"",
			"satellite(X,Y) :-",
			"  orbits(X,Y),",
			"  not(intermediate(X,Y)),", 
			"  not(star(Y)).",
			"",
			"planet(X) :-", 
			"  orbits(X,Y),", 
			"  star(Y),", 
			"  not(intermediate(X,Y)).",
			"",
			"intermediate(X,Y) :-", 
			"  orbits(X,Z), ",
			"  orbits(Z,Y). % This is correct",
			"%  orbits(Y,Z). % This is an error"
		],
		"query": "satellite(X,earth)"
	},
	{
		"name": "Pfade in einem Graphen",
		"description": "Ein einf%uuml;hrendes Beispiel zur Rekursion in Datalog.",
		"source": "Datalog Educational System - User's Manual",
		"ruleset": [
			"% Paths in a Graph",
			"edge(a,b).",
			"edge(a,c).",
			"edge(b,a).",
			"edge(b,d).",
			"",
			"path(X,Y) :- path(X,Z), edge(Z,Y).",
			"path(X,Y) :- edge(X,Y)."
		],
		"query": "path(X,Y)"
	},
	{
		"name": "Muencher U-Bahn (U2 und U6)",
		"description": "Teile des muencher U-Bahn-Netzes.",
		"source": "",
		"ruleset": [
			"% Fakten (Linien U2 und U6)",
			"direkt(feldmoching,hasenbergl,u2).",
			"direkt(hasenbergl,duelferstrasse,u2).",
			"direkt(duelferstrasse,harthof,u2).",
			"direkt(harthof,am_hart,u2).",
			"direkt(am_hart,frankfurter_ring,u2).",
			"direkt(frankfurter_ring,milbertshofen,u2).",
			"direkt(milbertshofen,scheidplatz,u2).",
			"direkt(scheidplatz,hohenzollernplatz,u2).",
			"direkt(hohenzollernplatz,josephsplatz,u2).",
			"direkt(josephsplatz,theresienstrasse,u2).",
			"direkt(theresienstrasse,koenigsplatz,u2).",
			"direkt(koenigsplatz,hauptbahnhof,u2).",
			"direkt(hauptbahnhof,sendlinger_tor,u2).",
			"direkt(sendlinger_tor,fraunhoferstrasse,u2).",
			"direkt(fraunhoferstrasse,kolumbusplatz,u2).",
			"direkt(kolumbusplatz,silberhornstrasse,u2).",
			"direkt(silberhornstrasse,unterbergstrasse,u2).",
			"direkt(unterbergstrasse,giesing,u2).",
			"direkt(giesing,karl_preis_platz,u2).",
			"direkt(karl_preis_platz,innsbrucker_ring,u2).",
			"direkt(innsbrucker_ring,josephsburg,u2).",
			"direkt(josephsburg,kreillerstrasse,u2).",
			"direkt(kreillerstrasse,trudering,u2).",
			"direkt(trudering,moosfeld,u2).",
			"direkt(moosfeld,messestadt_west,u2).",
			"direkt(messestadt_west,messestadt_ost,u2).",
			"",
			"direkt(garching_forschungszentrum,garching,u6).",
			"direkt(garching,garching_hochbrueck,u6).",
			"direkt(garching_hochbrueck,froettmanning,u6).",
			"direkt(froettmanning,kieferngarten,u6).", 
			"direkt(kieferngarten,freimann,u6).",
			"direkt(freimann,studentenstadt,u6).", 
			"direkt(studentenstadt,alte_heide,u6).", 
			"direkt(alte_heide,nordfriedhof,u6).",
			"direkt(nordfriedhof,dietlindenstrasse,u6).",
			"direkt(dietlindenstrasse,muenchner_freiheit,u6).",
			"direkt(muenchner_freiheit,odeonsplatz,u6).",
			"direkt(odeonsplatz,marienplatz,u6).",
			"direkt(marienplatz,sendlinger_tor,u6).", 
			"direkt(sendlinger_tor,goetheplatz,u6).",
			"direkt(goetheplatz,poccistrasse,u6).",
			"direkt(poccistrasse,implerstrasse,u6).",
			"direkt(implerstrasse,harras,u6).",
			"direkt(harras,partnachplatz,u6).",
			"direkt(partnachplatz,westpark,u6).",
			"direkt(westpark,holzapfelkreuth,u6).",
			"direkt(holzapfelkreuth,haderner_stern,u6).",
			"direkt(haderner_stern,grosshadern,u6).",
			"direkt(grosshadern,klinikum_grosshadern,u6).",
			"",
			"bidirekt(V,N,L) :- direkt(V,N,L).",
			"bidirekt(V,N,L) :- direkt(N,V,L).",
			"",
			"indirekt(V,N) :- bidirekt(V,N,_).",
			"indirekt(V,N) :- bidirekt(V,X,_),indirekt(X,N), N\\=V."
		],
		"query": "indirekt(garching,trudering)"
	}
]
